implemented support for custom components to be used in place of the …
reactabular/searchtabular pull request #1
Opened 2016-12-18 01:16 UTC by tpizza

@bebraw Here's my implementation for passing a custom component through to Field in searchtabular.

2016-12-19 18:10 UTC, git-toni commented
@tpizza thanks for the PR, I'll wait for @bebraw 's opinion before merging. I've been a bit busy with other things and I'm not sure how much he's using `searchtabular` in general for reactabular` :)

2016-12-19 18:13 UTC, bebraw requested changes
Can you add the new option to the readme as well? Looking good otherwise.

2016-12-19 18:13 UTC, bebraw commented on .gitignore
> +.idea
Can you drop this ignore? It's too specific to belong here.

2016-12-20 03:38 UTC, tpizza commented
@bebraw IntelliJ ignore has been removed.

2016-12-20 03:44 UTC, tpizza commented
Ahhh, I just saw the request for the readme update.  Will make that revision now.

2016-12-20 09:45 UTC, merged

2016-12-20 10:41 UTC, bebraw commented
Published as `1.3.0`. Thanks.

2016-12-21 09:08 UTC, git-toni commented
@bebraw Oh, now I see mixed `selectabular`(which I collaborated a bit with) with `searchtabular`, you must have thought I'm crazy : )

2016-12-21 09:09 UTC, bebraw commented
@git-toni No probs.